### ISSUE TITLE
[Feature Request] Make the streams/streamers list mouse scrollwheel-able

### ISSUE THREAD

**Issue by garoto** [mmozeiko/TwitchNotify#11]
If possible of course. Having to move the mouse and click at the up and down arrows isn't very ergonomic :)

**Comment by mmozeiko** [comment]
Unfortunately that is how standard windows context menu works. No mouse wheel scrolling. Best you can do is up & down arrow keys on keyboard.
Changing this would require custom window implementation for context menu. Which is too much work...

**Comment by garoto** [comment]
Understandable. Appreciate your little program nonetheless.
