### ISSUE TITLE
JSON parse error!

### ISSUE THREAD

**Issue by azizLIGHT** [mmozeiko/TwitchNotify#2]
I am getting a system tray notification that says JSON parse error! . This seems to happen randomly, I cannot tell what is causing it.

I attached my TwitchNotify.txt

[TwitchNotify.txt](https://github.com/mmozeiko/TwitchNotify/files/2023832/TwitchNotify.txt)

**Comment by azizLIGHT** [comment]
When I exited TwitchNotify, I got a error and a dump file was produced. Maybe this could help diagnose the issue?

[CrashDump_TwitchNotify_2018_5_21_19_38_32.zip](https://github.com/mmozeiko/TwitchNotify/files/2023866/CrashDump_TwitchNotify_2018_5_21_19_38_32.zip)

**Comment by mmozeiko** [comment]
I have seen few times json parse error when my network were unstable or when I resumed PC from sleep and TwitchNotify could not access network... Its pretty much harmless error message, but yeah, maybe there should be better error description. If you want to debug this, I suggest to add code that dumps received json string to file (each time different), and then when you see error message pop up, then examine latest json file to see what is wrong with it - it probably will have error message inside.

As for  crash - what is Toaster.dll?	"C:\Users\BillG\Downloads\TwitchNotify\Toaster.dll" ?
This is on call-stack in minidump.

**Comment by azizLIGHT** [comment]
> As for crash - what is Toaster.dll? "C:\Users\BillG\Downloads\TwitchNotify\Toaster.dll" ?
This is on call-stack in minidump. Crash happens when function from this dll tries to do something.

OK, it looks like I'm using a fork and not your actual release!! Sorry, that was my mistake... So this issue is probably not relevant here. I will close it.
Unfortunately I cannot use your release due to it being incompatible with 32 bit systems

**Comment by mmozeiko** [comment]
You can simply recompiled code with 32-bit compiler and it will work fine. I do not use anything that is 64-only. I put up only 64-bit binary because it is pretty rare to find 32-bit only systems.

Here's a 32-bit binary I just now compiled: [TwitchNotify32.zip](https://raw.githubusercontent.com/wiki/mmozeiko/TwitchNotify/TwitchNotify32.zip)
