### ISSUE TITLE
Feature request: open browser instead of player

### ISSUE THREAD

**Issue by gorro123** [mmozeiko/TwitchNotify#9]
I don't want to start a new "issue" - I'm new to github and I don't know how to contact you either. But here I am. Hopefully the right place to request a feature.

Instead of autoplay with the player, could I somehow just start my a saved .url file or sth similar that links me to the streamer? The player doesn't support prime, so it's blasted with the default twitch ads.

Edit: below

**Comment by mmozeiko** [comment]
You can uncheck "mpv Player" checkbox, then clicking on users will open playback in browser.

**Comment by gorro123** [comment]
Sorry, I misspelled it horibly. What I meant is to autostart the browser with the streamer after he went live. E.g. a .url-file saved in the same folder, that get's launched as soon as the stream starts.

**Comment by mmozeiko** [comment]
Doing automatic actions would be better as separate program - listening events on websocket and then performing whatever custom actions needed. Putting too much custom code for specific actions is a bit too much overhead for a simple gui notification utility like this.
